@baseUrl=http://localhost:3000/api
@resourceName=categories
#Cateogries

# @name getAll
GET {{baseUrl}}/{{resourceName}}
###

# @name add
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
    "name": "Laptop"
}

###
# @name update
PATCH {{baseUrl}}/{{resourceName}}/Tn355Z5
Content-Type: application/json

{
    "name": "New Laptop 2"
}

###

# @name Remove
DELETE  {{baseUrl}}/{{resourceName}}/0SyRd1x